extra_css:
- stylesheets/extra.css
markdown_extensions:
- admonition
- codehilite
- toc
nav:
- 主页: index.md
- 1 介绍: section1/index.md
- 2 安装与设置:
  - 下载 PMTaro 安装程序 & 运行设置向导: section2/installation.md
  - 激活: section2/activation.md
  - 更新: section2/update.md
  - 删除: section2/uninstallation.md
- 3 软件操作指南:
  - 欢迎页面: section3/homepage.md
  - 数据集页面: section3/dataset_page.md
  - 项目页面: section3/project_page.md
  - 阅片页面: section3/screening_page.md
  - 插件页面: section3/plugin_page.md
  - 工作流界面: section3/workflow_page.md



plugins:
- search
site_name: PMTaro Manual
theme: readthedocs
docs_dir: markdowns
site_dir: docs
use_directory_urls: false