site_name: PMTaro User Muanual
nav:
  - Home: index.md
  - Parsing: user_manual/parsing.md
  - Cleaning: user_manual/cleaning.md
  - Post-processing: user_manual/post-processing.md
  - Import & Export: user_manual/import_export.md
  - Setting: user_manual/setting.md
theme: readthedocs
